# Generated by Django 4.1.5 on 2023-01-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Times",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cidade", models.CharField(max_length=255)),
                ("titulos", models.CharField(max_length=255)),
                ("craque", models.CharField(max_length=255)),
            ],
        ),
    ]
